### ISSUE TITLE
Re installed windows history is gone 

### ISSUE THREAD

**Issue by not-me-is** [swift-kim/SongPlayHistory#1]
after reinstalling windows i have noticed that my history is gone 
game install drive where beat saber is installed on  is untouched

**Comment by swift-kim** [comment]
The local data file can be located at `(Beat Saber directory)\UserData\SongPlayHistory.json`. If the file is gone or overwritten, unfortunately it cannot be restored from anywhere. Are you using Steam version of Beat Saber? (This mod is only tested for Steam version.) Do you use ModAssistant to install and update your mods?

**Comment by not-me-is** [comment]
i have found the problem the plugin works great no issues and the SongPlayHistory.json was still there and not overwritten the issue was that i didn't copy  C:\Users\Username\AppData\LocalLow\Hyperbolic Magnetism\Beat Saber to my new user account now all my stats are back

**Comment by swift-kim** [comment]
Good news!
