### ISSUE TITLE
Plugin breaks end-of-song UI when SongPlayData.json is malformed.

### ISSUE THREAD

**Issue by hedo29** [swift-kim/SongPlayHistory#2]
On finishing a song, this plugin seems to intercept the select-a-menu-button function and try to write/read to SongPlayData.json. If this file is corrupted (not parse-able) it prevents the player from being able to finish their song and return to the song select menu.

I've tested this a few times. The initial issue came from an overheat causing an unexpected shutdown. On restart, I couldn't get back to the main menu after completing a song. I then started loading in mods one by one -- the only time it became an issue was when I was restoring my user data and realized my SongPlayData.json was completely corrupted and had no readable text in it.

The simple workaround is to delete this file and the game works properly. But it would be significantly better if there was a sanity checker making sure that this file was readable.

Unfortunately I no longer have a copy of the corrupted file, but it's just a very long binary file filled with 0s.

**Comment by swift-kim** [comment]
You're right. Soft-locking the game should be avoided in any case. I'll check if I can reproduce this issue (if there's a stack trace from the exception it will help). Thanks for reporting!

**Comment by swift-kim** [comment]
I wasn't actually able to reproduce this. If you have a corrupted data file, the plugin should fail fast on initialization and be automatically deactivated without doing anything. I'll add some error check logic for IO operations anyway. Sorry for the inconvenience.

**Comment by hedo29** [comment]
Most of my stuff was wiped in trying out multiple clean installs, so unfortunately I don't have a stack trace (only the actual file that caused me to have problems). It could have been a large number of things but deleting this particular file is what fixed it for me. For what it's worth, I vaguely recall "Refreshing song information..." followed by a couple critical unity exceptions in the verbose output every time I'd trigger over a button on the result screen.

But I appreciate you looking into this! I have to get in the habit of taking logs *before* I start troubleshooting.

**Comment by goopsie** [comment]
I've just encountered this issue, SongPlayData.json is completely empty
[_latest.log](https://github.com/swift-kim/SongPlayHistory/files/4843364/_latest.log)
[songplayhistory_latest.log](https://github.com/swift-kim/SongPlayHistory/files/4843366/_latest.log)

**Comment by swift-kim** [comment]
@goopsie Thanks for reporting. I'll take a look.

**Comment by swift-kim** [comment]
It looks like an empty data file leads to such an unexpected behavior. I think I have tested this case before (maybe the IPA plugin loader has been updated to work differently?) but anyway I have to add some logic/unit tests to deal with this case (check if the data file is empty and restore from a backup file). Sorry for the inconvenience.

@goopsie Was your backup file (SongPlayData.bak) also empty?

**Comment by goopsie** [comment]
SongPlayData.bak isn't empty

**Comment by swift-kim** [comment]
@goopsie Good news. I'll make a fix to use that backup when anything goes wrong. Until then you can just rename the file to .json to make the plugin work again.

**Comment by swift-kim** [comment]
I've made a new [release](https://github.com/swift-kim/SongPlayHistory/releases/tag/1.2.3) with the above fix, but it will not be available on BeatMods until the next major game update.
