### ISSUE TITLE
Song title is duplicated on song list menu

### ISSUE THREAD

**Issue by chrislee0419** [swift-kim/SongPlayHistory#3]
In the song menu, if a level TableCell displays the upvote/downvote icon, the song name will be duplicated onto the song author/level author text.

![image](https://user-images.githubusercontent.com/14931856/80337027-ae649080-880d-11ea-97ea-0d7dd1e055a3.png)

In the above image, both Black Ray and Bad Apple are affected. Below is what it should look like:
![image](https://user-images.githubusercontent.com/14931856/80337219-334faa00-880e-11ea-916f-d61644ef2d78.png)

The offending line appears to be [here](https://github.com/swift-kim/SongPlayHistory/blob/master/SongPlayHistory/HarmonyPatches/LevelListTableCell.cs#L69), but I haven't built and/or tested the fix so I can't know for certain.

**Comment by swift-kim** [comment]
Looks obviously like a mistake. Will be fixed in the next release.

**Comment by swift-kim** [comment]
Fixed by 87ce9e9051b219836029186ae15e3f71d0f8a75a. I don't know why I didn't notice this before. Thanks for reporting!
