### ISSUE TITLE
Mod doesn't show up in ModAssistant with Beatsaber v 1.12.2

### ISSUE THREAD

**Issue by Deaburo** [swift-kim/SongPlayHistory#6]
As the title says.
your Mod doesn't show up in the ModAssistant when i say "mods for Version 1.12.2"
Did i mess something up?

**Comment by swift-kim** [comment]
No, you didn't do anything wrong. The mod is under testing and not submitted to BeatMods yet. The [1.4.2 release](https://github.com/swift-kim/SongPlayHistory/releases/tag/1.4.2) will be submitted tomorrow if no additional bugs are found.

**Comment by Deaburo** [comment]
Thank you for the fast reaction and for the information.
I am glad that i didn't break anything and looking forward for your mod :)
